# Simple BERTopic Pipeline (Hippocorpus)

1. Configure topic mode and load data.
2. Optional BERTopic-native LLM representation for topic names during modeling.
3. Fit BERTopic and export topic outputs.
4. Optional post-fit LLM suggestion and review workflow for topic names.
5. Label the full Hippocorpus with regex rules.
6. Append labels to reduced datasets by statement index.

In [15]:
from pathlib import Path
import os
import re
import pandas as pd
from bertopic import BERTopic
from bertopic.representation import KeyBERTInspired
from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import CountVectorizer

## Step 1: Configure topic fitting mode and load data
- Set `TOPIC_MODE` (`'hdbscan'` or `'kmeans'`).
- Configure paths and `APPEND_TARGETS`.
- Load Hippocorpus into `hip` and `docs`.

In [16]:
DATA_DIR = Path('../data')
HIPPOCORPUS_PATH = DATA_DIR / 'hippocorpus.csv'

# Topic fitting mode: 'hdbscan' (default) or 'kmeans'
TOPIC_MODE = 'hdbscan'
KMEANS_N_CLUSTERS = 30

OUTPUT_DOCS_PATH = DATA_DIR / ('output_k_means.csv' if TOPIC_MODE == 'kmeans' else 'output.csv')
OUTPUT_TOPICS_PATH = DATA_DIR / ('topic_info_k_means.csv' if TOPIC_MODE == 'kmeans' else 'topic_info.csv')
LABELED_HIPPOCORPUS_PATH = DATA_DIR / 'hippocorpus_labeled.csv'

# Add or remove targets here whenever you want to append labels to new files.
APPEND_TARGETS = [
    {'input': 'final.csv', 'index_col': 'os_id', 'output': 'final_labeled.csv'},
    {'input': 'final_deltamax.csv', 'index_col': 'os_id', 'output': 'final_deltamax_labeled.csv'},
    {'input': 'gemma4_raw.csv', 'index_col': 'statement_id', 'output': 'gemma4_raw_labeled.csv'},
    {'input': 'llama3.3_raw.csv', 'index_col': 'statement_id', 'output': 'llama3.3_raw_labeled.csv'},
    {'input': 'qwen3_raw.csv', 'index_col': 'statement_id', 'output': 'qwen3_raw_labeled.csv'},
    {'input': 'study1_final.csv', 'index_col': 'statement_id', 'output': 'study1_final_labeled.csv'},
    {'input': 'hippocorpus_test_truncated_80_100.csv', 'index_col': 'index', 'output': 'hippocorpus_test_truncated_80_100_labeled.csv'},
]

hip = pd.read_csv(HIPPOCORPUS_PATH, sep=',')
docs = hip['text'].astype(str).tolist()
print(f'Hippocorpus rows: {len(hip):,}')

Hippocorpus rows: 5,047

## Step 2 (Optional): Use BERTopic LLM representation model

This is the BERTopic-native approach to naming topics during modeling.

- Set `USE_BERTOPIC_LLM_REPRESENTATION = True`.
- Export `OPENAI_API_KEY` before running.
- If disabled or unavailable, the pipeline falls back to `KeyBERTInspired`.

In [ ]:
USE_BERTOPIC_LLM_REPRESENTATION = False
BERTOPIC_LLM_MODEL = 'gpt-4.1-mini'

REPRESENTATION_MODEL = KeyBERTInspired()

if USE_BERTOPIC_LLM_REPRESENTATION:
    try:
        from openai import OpenAI
        from bertopic.representation import OpenAI as BERTopicOpenAI
    except ImportError as exc:
        raise ImportError(
            'Install openai to use BERTopic OpenAI representation: pip install openai'
        ) from exc

    api_key = os.getenv('OPENAI_API_KEY', '')
    if not api_key:
        raise ValueError('Missing OPENAI_API_KEY environment variable.')

    client = OpenAI(api_key=api_key)
    prompt = (
        'You are an expert topic modeler. Given topic keywords, generate one concise '\
        'human-readable topic label (2-3 words). Return only the label text.'
    )
    REPRESENTATION_MODEL = BERTopicOpenAI(
        client,
        model=BERTOPIC_LLM_MODEL,
        prompt=prompt,
        chat=True,
    )
    print(f'Using BERTopic OpenAI representation model: {BERTOPIC_LLM_MODEL}')
else:
    print('Using default BERTopic representation model: KeyBERTInspired')

## Step 3: Fit topics

In [ ]:
representation_model = REPRESENTATION_MODEL if 'REPRESENTATION_MODEL' in globals() else KeyBERTInspired()

if TOPIC_MODE == 'kmeans':
    cluster_model = KMeans(n_clusters=KMEANS_N_CLUSTERS, random_state=42)
    vectorizer_model = CountVectorizer(stop_words='english')

    topic_model = BERTopic(
        hdbscan_model=cluster_model,
        vectorizer_model=vectorizer_model,
        representation_model=representation_model,
    )
    topics, probs = topic_model.fit_transform(docs)

    # Old kmeans pipeline: no outlier reduction step
    hip['topic'] = topics
else:
    topic_model = BERTopic(representation_model=representation_model)
    topics, probs = topic_model.fit_transform(docs)

    # Old hdbscan pipeline: reduce outliers then update topic representations
    reduced_topics = topic_model.reduce_outliers(docs, topics)
    hip['topic'] = reduced_topics
    topic_model.update_topics(docs, topics=reduced_topics)

hip.to_csv(OUTPUT_DOCS_PATH, index=False)
topic_info = topic_model.get_topic_info()
topic_info.to_csv(OUTPUT_TOPICS_PATH, index=False)

print(f'Saved: {OUTPUT_DOCS_PATH}')
print(f'Saved: {OUTPUT_TOPICS_PATH}')
topic_info.head(10)

## Step 4 (Optional Alternative): Post-fit LLM topic name suggestions

Use this step only if you want a separate review/apply loop after fitting topics.

- Set `USE_LLM_TOPIC_NAMES = True`.
- Export your key before running: `export OPENAI_API_KEY=...`
- Review `data/topic_name_suggestions.csv` before applying any labels.

The next code cell only creates suggestions; it does not change your dataset labels automatically.

In [ ]:
import json
import os
from urllib import error, request

# Set to True to request suggested topic names from an OpenAI-compatible API.
USE_LLM_TOPIC_NAMES = False
LLM_API_KEY = os.getenv('OPENAI_API_KEY', '')
LLM_BASE_URL = 'https://api.openai.com/v1'
LLM_MODEL = 'gpt-4.1-mini'
LLM_OUTPUT_PATH = DATA_DIR / 'topic_name_suggestions.csv'


def build_topic_payload(topic_info_df, max_topics=40):
    keep = topic_info_df[topic_info_df['Topic'] != -1].head(max_topics).copy()
    payload = []
    for row in keep.itertuples(index=False):
        representation = row.Representation
        if not isinstance(representation, list):
            representation = [tok.strip() for tok in str(representation).strip('[]').replace("'", '').split(',') if tok.strip()]
        payload.append(
            {
                'topic_id': int(row.Topic),
                'count': int(row.Count),
                'current_name': str(row.Name),
                'keywords': representation[:10],
            }
        )
    return payload


if not USE_LLM_TOPIC_NAMES:
    print('LLM naming disabled. Set USE_LLM_TOPIC_NAMES = True to generate suggestions.')
else:
    if not LLM_API_KEY:
        raise ValueError('Missing OPENAI_API_KEY environment variable.')

    topics_payload = build_topic_payload(topic_info)
    prompt = {
        'task': 'Suggest short, human-readable labels for BERTopic topics.',
        'rules': [
            'Label length: 2-5 words.',
            'Be specific and concrete.',
            'Avoid numbering in the label text.',
            'Return valid JSON only.',
        ],
        'return_format': {
            'topic_names': {
                '<topic_id>': '<suggested_label>'
            }
        },
        'topics': topics_payload,
    }

    body = {
        'model': LLM_MODEL,
        'temperature': 0.2,
        'messages': [
            {'role': 'system', 'content': 'You rename topic-model clusters for analytics reporting.'},
            {'role': 'user', 'content': json.dumps(prompt)},
        ],
    }

    req = request.Request(
        f"{LLM_BASE_URL.rstrip('/')}/chat/completions",
        data=json.dumps(body).encode('utf-8'),
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {LLM_API_KEY}',
        },
        method='POST',
    )

    try:
        with request.urlopen(req, timeout=90) as resp:
            raw = resp.read().decode('utf-8')
    except error.HTTPError as exc:
        detail = exc.read().decode('utf-8', errors='ignore')
        raise RuntimeError(f'LLM API error {exc.code}: {detail}') from exc

    response_json = json.loads(raw)
    content = response_json['choices'][0]['message']['content']

    try:
        parsed = json.loads(content)
    except json.JSONDecodeError:
        start = content.find('{')
        end = content.rfind('}')
        if start == -1 or end == -1:
            raise ValueError('Model response was not valid JSON.')
        parsed = json.loads(content[start : end + 1])

    mapping = parsed.get('topic_names', parsed)

    suggestions = []
    for topic_id, label in mapping.items():
        try:
            topic_int = int(topic_id)
        except (TypeError, ValueError):
            continue
        suggestions.append({'Topic': topic_int, 'suggested_label': str(label).strip()})

    suggestion_df = pd.DataFrame(suggestions).drop_duplicates(subset='Topic')
    suggestion_df = topic_info[['Topic', 'Name', 'Count']].merge(suggestion_df, on='Topic', how='left')
    suggestion_df.to_csv(LLM_OUTPUT_PATH, index=False)

    print(f'Saved: {LLM_OUTPUT_PATH}')
    suggestion_df.head(20)

In [ ]:
# Optional: apply reviewed topic names back to topic_info.
# Set APPLY_LLM_NAMES = True only after checking LLM_OUTPUT_PATH.
APPLY_LLM_NAMES = False
FINAL_TOPIC_INFO_PATH = DATA_DIR / ('topic_info_k_means_named.csv' if TOPIC_MODE == 'kmeans' else 'topic_info_named.csv')

if not APPLY_LLM_NAMES:
    print('Apply step disabled. Set APPLY_LLM_NAMES = True to write named topic info.')
else:
    if not LLM_OUTPUT_PATH.exists():
        raise FileNotFoundError(f'Missing suggestion file: {LLM_OUTPUT_PATH}')

    reviewed = pd.read_csv(LLM_OUTPUT_PATH)
    required_cols = {'Topic', 'suggested_label'}
    missing_cols = required_cols.difference(reviewed.columns)
    if missing_cols:
        raise ValueError(f'Suggestion file is missing columns: {sorted(missing_cols)}')

    reviewed = reviewed[['Topic', 'suggested_label']].copy()
    reviewed['Topic'] = pd.to_numeric(reviewed['Topic'], errors='coerce').astype('Int64')
    reviewed['suggested_label'] = reviewed['suggested_label'].astype(str).str.strip()
    reviewed = reviewed.dropna(subset=['Topic'])
    reviewed = reviewed[reviewed['suggested_label'].ne('')]
    reviewed = reviewed[reviewed['suggested_label'].str.lower().ne('nan')]
    reviewed = reviewed.drop_duplicates(subset='Topic', keep='last')

    topic_info_named = topic_info.copy()
    topic_info_named = topic_info_named.merge(
        reviewed.rename(columns={'suggested_label': 'llm_label'}),
        on='Topic',
        how='left',
    )
    topic_info_named['final_name'] = topic_info_named['llm_label'].fillna(topic_info_named['Name'])

    topic_info_named.to_csv(FINAL_TOPIC_INFO_PATH, index=False)
    print(f'Saved: {FINAL_TOPIC_INFO_PATH}')
    topic_info_named[['Topic', 'Name', 'llm_label', 'final_name', 'Count']].head(20)

## Step 5: Create regex rules from inspected topics and label full Hippocorpus
Edit only `RULES` below. First match wins.

In [86]:
RULES = [
    (1, 'Funeral/Death', re.compile(
        r'\b(funeral|wake(?= service| ceremony|\s+for\b)|\bburial|cremat(?:e|ion|ed)|cemeter(?:y|ies)|(?:he|she|they|someone|my\s+\w+)\s+died|passed away|grief|mourning|eulog(?:y|ies))\b',
        re.I,
    )),
    (2, 'NaturalDisaster/Weather', re.compile(
        r'\b(hurricane|tornado|earthquake|aftershock|wildfire|'
        r'evacuat(?:e|ed|ion)|'
        r'flash\s+flood(?:ed|ing)?|flood(?:ed|ing)\s+(?:the\s+)?(?:town|street|city|neighborhood|area|region)|'
        r'house\s+flooded|'
        r'water\s+damage\s+(?:from|caused\s+by)\s+(?:the\s+)?(?:hurricane|flood|storm|rain|hail)|'
        r'storm\s+surge|blizzard|ice\s+storm|hailstorm)\b',
        re.I,
    )),
    (3, 'Hospital/Injury', re.compile(
        r'\b(hospital(?:ized)?|(?:my\s+)?doctor|dr\.(?=\s+[A-Z])|'
        r'(?:registered\s+)?nurse(?=\s+(?:said|told|came|checked|practitioner))|'
        r'clinic|emergency\s+room|ambulance|surgery|chemo(?:therapy)?|tumou?r|'
        r'(?:physical\s+)?therapy|medication|diagnos(?:is|ed)|'
        r'injur(?:y|ed)|wound(?:ed)?|stitch(?:es)?|'
        r'(?:had\s+(?:a\s+)?|with\s+(?:a\s+)?)broken\s+(?:arm|leg|bone|wrist|ankle|rib|collarbone|toe|finger|jaw|nose|hip)|'
        r'fracture(?:d)?|sprain(?:ed)?|concussion|'
        r'(?:got\s+(?:a\s+|an\s+)?|developed\s+(?:a\s+|an\s+)?|treated\s+for\s+(?:a\s+|an\s+)?)infection)\b',
        re.I,
    )),
    (4, 'Gambling', re.compile(
        r'\b(casino|gambl(?:e|ing|er)|'
        r'(?:placed|made|setting)\s+(?:a\s+)?wager(?:\s+on)?|'
        r'poker|blackjack|roulette|'
        r'(?:won\s+the\s+)?lottery|winnings?|jackpot|'
        r'won\s+(?:big|a\s+lot\s+of\s+)?money)\b',
        re.I,
    )),
    (5, 'Pets', re.compile(
        r'\b((?:my\s+)?dog|puppy|(?:my\s+)?cat|kitten|(?:my\s+)?pets?|veterinarian|animal\s+hospital|'
        r'on\s+(?:a\s+|the\s+)leash|'
        r'adopt(?:ed|ing|ion)\s+(?:a\s+)?(?:dog|cat|pet|puppy|kitten)|'
        r'walking\s+(?:my\s+|the\s+)?dog|'
        r'took\s+(?:my\s+|the\s+)?(?:dog|cat)\s+to\s+the\s+vet)\b',
        re.I,
    )),
    (6, 'Concert/Music', re.compile(
        r'\b(concert|(?:played\s+a\s+)?gig|live\s+music|'
        r'(?:my\s+)?favorite\s+band|(?:the\s+)?band\s+(?:played|was|is|came|performed)|'
        r'music\s+festival|'
        r'setlist)\b',
        re.I,
    )),
    (7, 'Vacation/Trip', re.compile(
        r'\b(vacation|holiday(?!\s+(?:party|bonus|pay))|road\s+trip|travel(?:ed|ing|ler)?|(?:booked?\s+a?\s+)?flight|airport|hotel|resort|airbnb|beach(?=\s+(?:vacation|trip|house))?|hiking\s+trail|went\s+camping|'
        r'(?:rented?\s+(?:a\s+)?|stayed\s+in\s+(?:a\s+)?)cabin|'
        r'kayak(?:ing)?|rafting|national\s+park|skiing|snowboard(?:ing)?|surfing|paris|london|rome|new\s+york)\b',
        re.I,
    )),
    (8, 'Birthday', re.compile(
        r'\b((?:my\s+|his\s+|her\s+|their\s+)birthday|bday|'
        r'(?:my\s+|his\s+|her\s+|their\s+)\d{1,3}(?:st|nd|rd|th)?\s+birthday|'
        r'(?:hosted|threw)\s+(?:a\s+)?birthday(?:\s+party)?|'
        r'(?:good|great)\s+birthday|had\s+a\s+(?:good|great)\s+birthday|'
        r'birthday\s+(?:cake|party|dinner|celebration|candles|present(?:s)?|gift(?:s)?)|'
        r'blew\s+out\s+(?:the\s+)?candles)\b',
        re.I,
    )),
    (9, 'Children', re.compile(
        r'\b(newborn|toddler|'
        r'(?:my\s+)?child(?:ren)?|'
        r'(?:my\s+(?:kids?|children)|kids?\s+(?:are|were|have|had|need|started|love|go|went))|'
        r'pregnan(?:t|cy)|'
        r'expecting\s+(?:a\s+baby|our\s+(?:first|second|third))|'
        r'(?:she\s+)?went\s+into\s+labor|'
        r'delivery\s+room|'
        r'gave\s+birth|'
        r'(?:our|the|my)\s+baby(?:\s+(?:was\s+born|is\s+due|arrived|shower))?|'
        r'ultrasound|due\s+date|diapers?|daycare|crib|stroller)\b',
        re.I,
    )),
    (10, 'Work', re.compile(
        r'\b((?:my\s+)?(?:new\s+)?job|'
        r'at\s+work|'
        r'my\s+company|my\s+boss|my\s+manager|'
        r'coworkers?|colleagues?|'
        r'(?:at\s+the\s+)?office|'
        r'(?:work\s+)?shift(?:\s+at\s+work)?|'
        r'(?:got\s+a\s+)?promotion|(?:got\s+)?promoted|'
        r'(?:got|received|earned|given)\s+a\s+raise|'
        r'job\s+interview|'
        r'my\s+resum[eé]|\bcv\b|'
        r'(?:got\s+)?hired|(?:got\s+)?fired|laid\s+off|'
        r'quit\s+(?:my\s+)?(?:job|position)|'
        r'resign(?:ed|ation)?)\b',
        re.I,
    )),
    (11, 'School', re.compile(
        r'\b(university|college|'
        r'(?:high\s+|middle\s+|elementary\s+)?school|'
        r'campus|'
        r'my\s+class(?:es)?|'
        r'lecture(?:s)?|'
        r'(?:my\s+)?teacher|professor|homework|assignment(?:s)?|'
        r'(?:final\s+)?exam(?:s)?|'
        r'(?:school|course|university)\s+finals?|finals?\s+(?:at\s+school|week)|'
        r'graduat(?:e|ed|ion)|(?:got\s+my\s+)?degree|diploma|'
        r'graduation\s+ceremony)\b',
        re.I,
    )),
    (12, 'Home/Moving', re.compile(
        r'\b((?:bought|rented)\s+(?:a\s+)?(?:house|apartment|flat|condo)|'
        r'my\s+flat|condo|roommate(?:s)?|mortgage|'
        r'signed\s+(?:a\s+)?lease|'
        r'landlord|tenant|'
        r'moved\s+in(?:to)?|just\s+moved|'
        r'packing\s+(?:boxes|up\s+my\s+(?:stuff|things|apartment|house|flat))|'
        r'moving\s+(?:boxes|day|truck|company|houses|apartment)|'
        r'new\s+(?:place|apartment|house|home|flat))\b',
        re.I,
    )),
    (13, 'Relationships', re.compile(
        r'\b((?:my\s+)?(?:wife|husband|fianc(?:e|ée)|boyfriend|girlfriend)|'
        r'went\s+on\s+a\s+date|date\s+night|'
        r'(?:am\s+|I\'m\s+|been\s+)?single|'
        r'broke?\s+up|break\s*up|'
        r'asked\s+(?:her|him|them)\s+(?:to\s+marry|out)|'
        r'wedding|(?:our\s+|the\s+|my\s+)?engagement|propos(?:ed?|al)|'
        r'engagement\s+ring|fell\s+in\s+love)\b',
        re.I,
    )),
    (14, 'Sports', re.compile(
        r'\b(playoffs?|tournament|match|'
        r'(?:my\s+|the\s+)?(?:sports?\s+)?coach(?!\s+(?:bus|seat|class))|'
        r'(?:sports?\s+practice|team\s+practice)|'
        r'(?:ran|finished)\s+(?:a\s+)?(?:race|5k|10k|half\s+marathon|marathon|triathlon)|'
        r'marathon|triathlon|'
        r'(?:hit\s+the\s+)?gym|'
        r'baseball|basketball|soccer|football|tennis|hockey|'
        r'swim(?:ming)\s+(?:team|race|meet)|'
        r'cycling|went\s+running|'
        r'(?:lifting\s+)?weights?)\b',
        re.I,
    )),
    (15, 'Family', re.compile(
        r'\b((?:my\s+)?(?:mom|mother|mum|dad|father)|'
        r'(?:my\s+)?(?:step(?:mom|mother|dad|father)|parents?)|'
        r'(?:my\s+)?(?:sister|brother|siblings?|daughter|son)|'
        r'(?:my\s+)?(?:grandma|grandpa|grandmother|grandfather|aunt|uncle|cousins?|niece|nephew)|'
        r'family\s+reunion)\b',
        re.I,
    )),
    (16, 'Writing', re.compile(
        r'\b((?:kept?\s+(?:a\s+)?|keep(?:ing)?\s+(?:a\s+)?)diary|dear\s+diary|'
        r'(?:start(?:ed|ing)?\s+(?:a\s+)?|kept?\s+(?:a\s+)?|keep(?:ing)?\s+(?:a\s+)?)journal(?:ing)?|'
        r'(?:wrote|writing|finished)\s+(?:a\s+)?(?:story|poem|novel|book|chapter|manuscript)|'
        r'publish(?:ed|ing)\s+(?:a\s+)?(?:book|novel|poem|manuscript|chapter)|'
        r'chapter(?=\s+(?:\d+|of|in))|'
        r'manuscript|poems?|poetry|'
        r'went\s+to\s+(?:the\s+)?library)\b',
        re.I,
    )),
]

def label_text(text):
    if pd.isna(text):
        return 0, 'Other'
    for topic_id, topic_label, pattern in RULES:
        if pattern.search(str(text)):
            return topic_id, topic_label
    return 0, 'Other'

In [87]:
# Optional rule-priority override (first match still wins).
RULE_ORDER = [
    'Funeral/Death',
    'NaturalDisaster/Weather',
    'Money/Gambling',
    'Concert/Music',
    'Vacation/Trip',
    'Birthday',
    'Hospital/Injury',
    'Children',
    'Work',
    'School',
    'Home/Moving',
    'Relationships',
    'Sports',
    'Family',
    'Pets',
    'Writing',
]

priority = {label: idx for idx, label in enumerate(RULE_ORDER)}
RULES = sorted(RULES, key=lambda rule: priority.get(rule[1], len(priority)))
print('Applied RULE_ORDER priority. Pets now runs after Family in matching.')

Applied RULE_ORDER priority. Pets now runs after Family in matching.

In [88]:
hip = pd.read_csv(HIPPOCORPUS_PATH)
hip[['topic_id', 'topic_label']] = hip['text'].apply(lambda x: pd.Series(label_text(x)))
hip.to_csv(LABELED_HIPPOCORPUS_PATH, index=False)

print(f'Saved: {LABELED_HIPPOCORPUS_PATH}')
hip['topic_label'].value_counts(dropna=False).head(20)

Saved: ../data/hippocorpus_labeled.csv

topic_label
Vacation/Trip              853
Hospital/Injury            697
Work                       589
Children                   507
Relationships              467
Other                      403
Funeral/Death              384
School                     333
Family                     254
Birthday                   188
Concert/Music               91
Home/Moving                 83
Pets                        71
Sports                      69
NaturalDisaster/Weather     29
Gambling                    15
Writing                     14
Name: count, dtype: int64

In [46]:
# Quick regex audit: distribution, overlap, and sample hits
from textwrap import shorten

N_OVERLAP_PREVIEW = 20
N_SAMPLES_PER_TOPIC = 3
PREVIEW_WIDTH = 180

if 'hip' not in globals() or not {'text', 'topic_id', 'topic_label'}.issubset(hip.columns):
    if LABELED_HIPPOCORPUS_PATH.exists():
        hip = pd.read_csv(LABELED_HIPPOCORPUS_PATH)
    else:
        hip = pd.read_csv(HIPPOCORPUS_PATH)
        hip[['topic_id', 'topic_label']] = hip['text'].apply(lambda x: pd.Series(label_text(x)))

topic_distribution = (
    hip['topic_label']
    .value_counts(dropna=False)
    .rename_axis('topic_label')
    .reset_index(name='count')
)
topic_distribution['pct'] = (topic_distribution['count'] / len(hip) * 100).round(2)

print('Topic distribution:')
display(topic_distribution)

texts = hip['text'].fillna('').astype(str)
rule_hits = pd.DataFrame(
    {topic_label: texts.str.contains(pattern, na=False) for _, topic_label, pattern in RULES}
 )
rule_hits_count = rule_hits.sum(axis=1)
multi_hit_mask = rule_hits_count > 1

ambiguous_rows = hip.loc[multi_hit_mask, ['text', 'topic_label']].copy()
if not ambiguous_rows.empty:
    ambiguous_rows['matched_topics'] = rule_hits.loc[multi_hit_mask].apply(
        lambda row: [col for col, matched in row.items() if matched], axis=1
    )
    ambiguous_rows['text_preview'] = ambiguous_rows['text'].astype(str).apply(
        lambda s: shorten(s.replace('\n', ' '), width=PREVIEW_WIDTH, placeholder=' ...')
    )

    print(f'Potential overlap rows (matched >1 rule): {len(ambiguous_rows):,}')
    display(ambiguous_rows[['topic_label', 'matched_topics', 'text_preview']].head(N_OVERLAP_PREVIEW))

    print('\nFull text for overlap preview rows:')
    for i, row in enumerate(ambiguous_rows.head(N_OVERLAP_PREVIEW).itertuples(index=False), start=1):
        print(f"\n[{i}] assigned={row.topic_label} | matched={', '.join(row.matched_topics)}")
        print(row.text)
else:
    print('Potential overlap rows (matched >1 rule): 0')

print('\nSample texts per assigned topic:')
sample_parts = []
for _, group in hip[['topic_label', 'text']].dropna(subset=['text']).groupby('topic_label'):
    sample_parts.append(group.sample(min(N_SAMPLES_PER_TOPIC, len(group)), random_state=42))

samples = pd.concat(sample_parts, ignore_index=True) if sample_parts else pd.DataFrame(columns=['topic_label', 'text'])
samples['text_preview'] = samples['text'].astype(str).apply(
    lambda s: shorten(s.replace('\n', ' '), width=PREVIEW_WIDTH, placeholder=' ...')
)
display(samples[['topic_label', 'text_preview']].head(60))

Topic distribution:

                topic_label  count    pct
0                      Work    830  16.45
1             Vacation/Trip    788  15.61
2           Hospital/Injury    636  12.60
3                  Children    477   9.45
4             Funeral/Death    384   7.61
5             Relationships    365   7.23
6                      Pets    320   6.34
7                     Other    309   6.12
8                    School    240   4.76
9                    Family    180   3.57
10                 Birthday    155   3.07
11           Money/Gambling    129   2.56
12            Concert/Music     85   1.68
13              Home/Moving     55   1.09
14                   Sports     53   1.05
15  NaturalDisaster/Weather     29   0.57
16                  Writing     12   0.24

Potential overlap rows (matched >1 rule): 3,658

,topic_label,matched_topics,text_preview
0,Pets,"[Pets, Relationships, Sports, Family]",Rex needs time to learn and that's exactly wha...
1,Children,"[Children, Home/Moving, Relationships, Family]",About three weeks ago my best friend gets kick...
2,Funeral/Death,"[Funeral/Death, Work, Relationships, Family]","Two weeks ago, we buried my mother in law. It ..."
3,Hospital/Injury,"[Hospital/Injury, Work, Relationships]",So today my thoughts are I can not let this un...
4,Children,"[Children, School, Relationships, Family]",My son started college. We loaded up both of o...
5,Hospital/Injury,"[Hospital/Injury, Relationships, Sports]","My wife had always been a healthy person, alth..."
6,Hospital/Injury,"[Hospital/Injury, Sports, Family]","It's been a crazy year. Reflecting back, I fee..."
8,Work,"[Work, School, Relationships, Family]","Four months ago, I had a wild time going to a ..."
10,Work,"[Work, Family]",I recently hosted a bridal shower for my best ...
13,Vacation/Trip,"[Vacation/Trip, Relationships, Family]",A couple months ago my younger brother got mar...
15,Hospital/Injury,"[Hospital/Injury, Children, Relationships, Fam...",I was already two weeks overdue and I remember...
16,Hospital/Injury,"[Hospital/Injury, Children, Work, Relationship...",On July 4th I gave birth to my beautiful son. ...
19,Vacation/Trip,"[Vacation/Trip, School]","Today, I got together with my best friends. We..."
20,Work,"[Work, School]",I've always loved taking picture. As a teenage...
21,Children,"[Children, Work, Family]",I have been trying fo the last few years to ad...
23,Vacation/Trip,"[Vacation/Trip, Family]",I remember a recent event in June 2019. My Mom...
24,Work,"[Work, Relationships, Family]","About three months ago, my husband and I were ..."
25,Children,"[Children, Work, Relationships, Family]",About three months ago I had been putting in a...
26,Work,"[Work, Family]",The perfect summer day with my niece. The day ...
27,Vacation/Trip,"[Vacation/Trip, Family]","A couple weeks ago for July 4th, we went up to..."

Full text for overlap preview rows:

[1] assigned=Pets | matched=Pets, Relationships, Sports, Family
Rex needs time to learn and that's exactly what will make him feel part of the family.  My husband and i brought in a dog trainer and Rex is now so promising. He has learnt quite a lot and i am impressed on the speed at which he is learning. The last time we were at a park with our daughter and Rex helped us find her when we lost track of her as she rode her bike in the park. We heard Rex barking from a distant and we went running towards the direction of the sound. We were happy to find Rex and Stacy together under a tree.  On asking Stacy why she didn't come back, she announced that her bike had spoiled and could not move. She trusted that somehow we would go looking for her. It was such a good moment and we loved Rex even more. We have even bought him a new collar. It has his name written on it.  Rex is so promising.   There was this memorable night when burglars came home and were about to break in. Rex with all his courage took on them and managed to pin one down who is helping the police with investigations. Rex has become one of us and we value him so much. He has proved to be a member of the family and with a lot of love. In many instances, Rex has proved to be capable beyond our expectations.      Though he is proving his ability, we intend to retain the trainer for the full time intended. Rex is one of the finest German Shepherd i have come across. We love him so much.

[2] assigned=Children | matched=Children, Home/Moving, Relationships, Family
About three weeks ago my best friend gets kicked out of her house along with her child and she came to me for help. I gladly accepted her and her child to stay at my home rent free until she is ready to go on. My bestfriend and her husband had a huge falling out. I felt extremely guilty. I allowed her to stay at my house for three weeks now. All she has done for me is take and take from me without ever giving. I figured that she was hurt and not in a good place, so I allowed it. After day in and day out of her not cleaning after herself or her son, not helping around the house, and not being a decent roommate is where I feel like I could have done something. My bestfriend was hurt and I felt obligated to help her. Now I don't know if we will be friends after this whole ordeal. I allowed her to walk all over me because I felt bad, I let her not clean up after herself, and I allowed her to neglect her duty to her son. I feel like I am the one to blame because I took her in and fed her without trying to get her up and going. I gave her too much space. I should've been a better friend, instead I decided to let her do what she wanted. I do not know what to do with her. I want to kick her out, but how bad of a person could I be if I decided to do that. She has a child, nowhere to go, and no friends that will take her in as graciously as I have.

[3] assigned=Funeral/Death | matched=Funeral/Death, Work, Relationships, Family
Two weeks ago, we buried my mother in law. It was a sad day that day. My father had a few tears. My mother had a few more tears. My brothers and sisters all gave me a hug. I gave a speech about her life. She was an accountant. She always went to work with a smile. She always got the job done. She was the best accountant at the company. She had a few kids and a husband. They all loved her. She loved to eat cupcakes. She loved them if they had some sprinkles on them. We celebrated this by having a giant batch of cupcakes made for the burial. We all grabbed a cupcake and threw them into the grave before she was buried.

[4] assigned=Hospital/Injury | matched=Hospital/Injury, Work, Relationships
So today my thoughts are I can not let this unexpected Hip injury interfere with my quality of life or life style. I am in pain and uncomfortable but HAVE to get better soon. The sooner I heal and recover from this injury the sooner I can get back to doing the things I enjoy with my lovely wife. I WILL overcome this and once again get back to enjoying the things i once took for granted. I will work hard and make sure to do my part to participate in my recovery so I can get back to MY LIFE. I with my wife's support will achieve my goal in getting better. This hip injury that I obtained after being careless will not take from me. i will not allow it to. i know as important as it is for myself to recover it is important for my family as well. I will make sure to pay more attention when i am on the go. I will also make sure that i look down more often when walking so that I will not trip over anything of have any more unexpected falls. I will care for my body more. I will appreciate my functional abilities of my body more from now on. i will overcome this. I will be a victor in this journey of healing.

[5] assigned=Children | matched=Children, School, Relationships, Family
My son started college.  We loaded up both of our cars with all of his things and headed to his college which was 3 hours away.  This is our first child leaving for college so it is stressful, expensive and just sad.  It was even worse for me as my car's check engine light came on while we were driving him down. I had to say my goodbyes in a gas station parking lot which was less than ideal.  We managed to fit all of his stuff except his bike into one car and I drove back home in case something major was wrong with the car.  My wife finished driving him to school to unload all of his stuff.  My oldest daughter went with them to help but we didn't have room in that car for my younger daughter who I drove home.  I didn't even get to see his dorm room or campus or anything.  I miss him a lot as everything just seems different now that he is gone.  I text him regularly but it certainly isn't the same as seeing him all of the time.  He is coming back to visit on labor day so at least we have that going for us.  The car had some sort of electrical problem causing it to misfire, $800 later it is fixed.  My wife drove his bike down a week later.  The entire reason we took him to college early was for band camp.  He got accepted to the band but decided he didn't want to do it so turned them down.  Wish we had just waited 2 more weeks to move him in.

[6] assigned=Hospital/Injury | matched=Hospital/Injury, Relationships, Sports
My wife had always been a healthy person, although she was skinny. She would eat, but was not able to gain weight. I envied her ability because I could look at a donut and gain ten pounds. However, she was eating a lot, but was still losing weight. One day, we decided to bring my wife into the emergency room as she had fainting spells. When we arrived, she was diagnosed with a chronic autoimmune disease. That explains why she wasn't able to gain any weight. We always assumed it was her fast metabolism. The fainting spell was a blessing in disguise because it is a common symptom of this autoimmune disease. The doctor who diagnosed her has already scheduled outpatient services for my wife, and as long as she can manage her symptoms, she should be able to live a full life without any setbacks. Although this is disappointing, it will allow my wife to be more disciplined about her health and wellness. Truthfully, she has always been good about her health and wellness. I, on the other hand, have not been. I am hoping that her malaise motivates me to improve my health and wellness. I used to not care what I put into my body, but after this experience, I may start doing that in order to have longevity.

[7] assigned=Hospital/Injury | matched=Hospital/Injury, Sports, Family
It's been a crazy year. Reflecting back, I feel I've changed for the better. A year ago, I was discovering my brother's cancer diagnosis and doing soul searching. I treated him so horribly when he was sick, I was a real asshole. He deserved to have a supportive sister, not someone telling him he's making it all up and using his sickness as an excuse. I was so hard on him for so long, I wasn't sure he'd even forgive me... I wouldn't. We worked on our relationship and I supported him like I should have. It came up that he needed a bone marrow match. I immediately sent off my swabs, but it took almost 2 months to hear back. We were a match. We underwent the process and the doctor says I helped saved my brothers life. He has a real fighting chance now. We sobbed together. Reflecting on this year, I really got my act together. And as bad as it may sound, my brother's illness was instrumental to me going down the right path... and I'll be thankful to him for the rest of my life.

[8] assigned=Work | matched=Work, School, Relationships, Family
Four months ago, I had a wild time going to a family wedding. It has been the first time in a decade that we've been under the same roof. I talked to mom and she said she has been doing well. I talked to father and he told me he caught the biggest fish that week. I talked to my sister and she has gotten a job in a big advertising firm. I talked to my brother and he just graduated college with a job prospect. My older brother is getting married to a rich tycoon woman. He will be very happy with the mansion he is moving into. I hope he doesn't get too greedy. I hope his life will have meaning. At the party, I got a little too drunk. I threw up on my older brother. He got a little mad. He forgave me. We went home with many memories.

[9] assigned=Work | matched=Work, Family
I recently hosted a bridal shower for my best friend. The shower was at her mom's house. I arrived early to set up decorations. The caterer showed up and set up the food also. Once the guests arrived, everyone ate first. After everyone had a chance to enjoy their food, I began the games. There were three games in total. Each game winner received a prize. After the games were done, the bride-to-be opened her gifts. She received a lot of gifts. The most memorable gift was a gag gift from her coworkers. The bride-to-be did not realize it was a gag at the time, which made her reaction to opening the gift even funnier, because she was trying to maintain a serious face. After the gifts, guests socialized for a little long, took pictures, and said their goodbyes. I stayed after the guests had left to clean up. Once the shower was over, we got ready for the bachelorette party that was later that night. We went out to eat and then went to several bars.

[10] assigned=Vacation/Trip | matched=Vacation/Trip, Relationships, Family
A couple months ago my younger brother got married. I traveled back to my home town of St. Louis, Missouri for the event. I took my girlfriend along with me, it was her first trip to my home town ever.  The trip started out great, we picked up our rental car and went to grab a pizza. The following day was my brother's wedding ceremony. We thought it had all been planned out thoroughly, but it turns out that nobody had checked the weather report. The day of the wedding came, it started out sunny, a hot day in late July. Clear blue skies and not a cloud to be seen. We were all so optimistic about the big day. The ceremony was scheduled for 6 PM at sunset, so it would start to cool down and allow for some reprieve from the heat of the day. In theory, that was a great idea. However, when my girlfriend and I pulled out of the driveway we noticed something new that we hadn't seen yet on the trip. Storm clouds moving in fast, and lots of them. Dark gray giants rose onto the horizon at a frightening pace. Lighting was visible in the distance as we began our drive to the wedding venue. We hoped and prayed that the storm would blow the other way, an that the outdoor wedding venue would be spared from this particular storm. Would we be able to get away with having the ceremony in decent weather? It became a race with time. As we drove to the wedding ceremony, it felt as though the clouds were following us and growing larger. As we arrived, I greeted my brother in the parking lot and asked if he though it would rain. He said maybe, it depends how fast we can get this done. Everyone was present except for the minister, one of the few people who was completely essential to the process.  As the minister arrived, it finally began to rain. It was raining on my brother's wedding day, I couldn't believe it, but luckily the ceremony was completed and we had a wonderful sunny reception the next day.

[11] assigned=Hospital/Injury | matched=Hospital/Injury, Children, Relationships, Family
I was already two weeks overdue and I remember my back killing me because of how heavy my daughter was. Last year we just lost our grandmother because of her hitting her head on the floor. My grandma cared for me and my siblings when we were little. I was very young to remember but my parents used to tell me a lot of memories my grandma used to do when she was alive. The doctors said that my amniotic fluid was more than average. And I remember being too worried prior to my daughter's delivery. I had to get induced into pregnancy because it was taking too long. My husband and my siblings were there in the hospital with me. But I also felt that grandma was there with me making sure I was okay. During labor I was very pale and I feel like I was going to lose my daughter. It was excruciatingly painful but I wasn't concerned about me, I was concerned about my daughter's life. I was panicking but I felt my grandmother's presence in the operating room. It's almost as if she's whispering to me, "I'm here, granddaughter. Take a deep breath and it will be okay." And it turned out to be okay. My daughter is now four years old and she's very intelligent and very curious about the modern world. She's way too young to be curious about the things going on around her that I am afraid she might grow up and learn about the evils in the world very early. But I can sense that you are guiding her and protecting her, grandma.

[12] assigned=Hospital/Injury | matched=Hospital/Injury, Children, Work, Relationships, Family
On July 4th I gave birth to my beautiful son. It was one of the best days of my life. I went into labor early that  morning and had him in the afternoon. As soon as my water broke my husband and I headed straight to the hospital. My director came also. She met us there. The labor process was a bit painful but I got through it. My husband was alongside me every step of the way. He did a great job helping me manage my pain. I am so blessed to have given birth to a precious wonderful a amazing baby boy. He is one of the joys of my life. He gives me joy each day. The best job I could ever have is God trusting me to take care of him. I will do my best in every area and aspect. I love him do much. The doctors said I did amazing. They said I was one of their best patients in a very long time. J was so happy to hear that.

[13] assigned=Vacation/Trip | matched=Vacation/Trip, School
Today, I got together with my best friends. We met in high school, and almost right away became good friends. We haven't seen each other in a long time, and that's why we decided to come out for a good vacation. It was a lot of fun, and we did many things together. The beach was nice. And the weather was great. We swam, and told each other stories. My friends and I even build a sand castle together, even though I thought that was a little childish. But we had fun. And that's the most important part. We haven't seen each other in a while. So we had a lot to say. We enjoyed our time there, and had a blast. It was great. I'm never going to forget the time we spend together.

[14] assigned=Work | matched=Work, School
I've always loved taking picture. As a teenager, you never saw me without my Nikon. I was always in the photo lab at school. Even in my senior photo, I've got a camera around my neck. Becoming a professional photographer was a life long dream for me. Working at the photo mart in the mall in high school was my launch into my career. When I got hired onto the newspaper, I was extatic. But getting my first portrait published into a national magazine was a huge milestone. To see MY picture. Right there on the cover. I could never have imagined it. But there it was, my picture on the cover of Time Magazine. My name in the credits of Time freaking magazine! The sky is the limit. The last three months since my picture appeared, I've been getting calls from all around the world. The future is bright.

[15] assigned=Children | matched=Children, Work, Family
I have been trying fo the last few years to adopt a child. About 2 months ago, i received a phone call that ther was a newborn whose mother was a teenager and did not want to keep the baby. The adoptive agent, Ms Reynolds, stated that my application met all the requirements. she specifically sought me out given that i am a pediatric ICU nurse. s Reynolds continue to state that the child was born prematurely at 29 weeks. the child's mother was a drug addict and the child may have been exposed to heroin. At first i was worried, since i was not sure if i wanted to have such responsibility. I told her that i would call her back.  I spent the next day thinking about the decision to take the child or not. I then thought about my adoptive sister who was born disabled, whom my mother adopted and gave a better life. I thought about how much i loved my sister and would do anything for her. I called back Ms Reynolds and told her that I would take the newborn once she was out of ICU. Two weeks later i had a little bundle of joy in my arms. From the moment i first laid eyes on her, the water work broke and i couldn't stop crying. the next few days were very hard. Lizzy cried all the time. Eventually things improved. yes, it is still challenging. But i would do it all again.

[16] assigned=Vacation/Trip | matched=Vacation/Trip, Family
I remember a recent event in June 2019.  My Mom and I went on a birthday trip to South Carolina. We stayed at a bed and breakfast for 3 days. The bed and breakfast had a lot of good reviews, but we didn't feel that it was the best one we had been to so far! The service was not what was expected, but we had fun. The first night we ate dinner at a Japanese restaurant. Breakfast was prepared all mornings we were there. The other nights, we had Chinese and also ate in Savannah, GA. For fun, we went to a plantation and traveled to other cities, like Charleston and Savannah, GA.  After our stay at the bed and breakfast, we drove to my uncle's house in Georgia. The trip took about 8 hours from where we stayed in South Carolina. We stayed for a couple of days, then went home. We also ate dinner at a restaurant. Our relative gave us a tour around the city. It was very nice and comfortable there. It was a memorable trip, getting to see other states as we rode along.

[17] assigned=Work | matched=Work, Relationships, Family

                topic_label                                       text_preview
0                  Birthday  Not so long back, about three weeks ago, my hu...
1                  Birthday  Dear Diary, Today is my sisters 20th birthday....
2                  Birthday  I would like to share some of my unforgettable...
3                  Children  My husband and I got married on a bright sunny...
4                  Children  Three months ago, my best friend got married. ...
5                  Children  I was extremely excited when I became a father...
6             Concert/Music  I am very glad to share my most unforgettable ...
7             Concert/Music  I was ecstatic when my childhood friend called...
8             Concert/Music  I was recently at an outdoor concert with my d...
9                    Family  A week ago, I learned there is no treatment fo...
10                   Family  A few months ago my teenage daughter and I are...
11                   Family  Two months ago, I went to a family reunion. I ...
12            Funeral/Death  A few months ago, we took a vacation back to m...
13            Funeral/Death  Birthdays are usually some of the most fun tim...
14            Funeral/Death  Almost four months ago I received a phone call...
15              Home/Moving  Some time ago I had moved into my apartment. I...
16              Home/Moving  Several weeks afterward, the man came back int...
17              Home/Moving  I loved my old neighbors next door. Once a wee...
18          Hospital/Injury  But I had to learn to use CPR and quick, as th...
19          Hospital/Injury  Diary Entry, After a week of anxiety and fear ...
20          Hospital/Injury  It's been a really tough past few years, speci...
21           Money/Gambling  The most memorable event that has happened to ...
22           Money/Gambling  I recently watched the online live feed of an ...
23           Money/Gambling  My sister gave me $800 to buy a birthday gift ...
24  NaturalDisaster/Weather  Now that the dust has literally settled - It i...
25  NaturalDisaster/Weather  Man diary, yesterday I wrote about how great m...
26  NaturalDisaster/Weather  My diary entry for this day September 3rd 2019...
27                    Other  The Vermont I saw looking out of the Greyhound...
28                    Other  There was a recent event that happened last Tu...
29                    Other  Three weeks ago, I and a group of friends visi...
30                     Pets  It has been a rough two weeks, since the passi...
31                     Pets  As Charles Dickens said, "It was the best of t...
32                     Pets  2 months ago my heart was shattered, and I hav...
33            Relationships  Earlier this year, my wife and I were married....
34            Relationships  Today I found out that my wife is going forwar...
35            Relationships  And my best half is my wife. I did not think I...
36                   School  i am going to say about my friends get to gath...
37                   School  Two months ago, my son started college in anot...
38                   School  A few months back my son wanted to go Off-road...
39                   Sports  Two months ago my best friend and I got into a...
40                   Sports  About six months ago we had a sudden, and terr...
41                   Sports  so basically i was sitting in the living room ...
42            Vacation/Trip  Three months ago was the annual family vacatio...
43            Vacation/Trip  A few weeks ago I traveled to Bellevue, Washin...
44            Vacation/Trip  I can't stop thinking about that wonderful tri...
45                     Work  Three months ago i moved out of my parents hom...
46                     Work  I had to leave me job previously. All my cowor...
47                     Work  About a month ago I was wandering about this s...
48                  Writing  Dear Diary,I had the night of my life. it was ...
49                  Writing  Dear Diary,I have finally went to Thailand wit...
50                  Writing  Aug 8, 20199 p.m.Dear Diary,My day started wit...

## Step 6: Append labels to reduced datasets by statement index

In [94]:
hip_labeled = pd.read_csv(LABELED_HIPPOCORPUS_PATH)

# Statement index alignment in the labeled Hippocorpus
hip_labeled['index'] = hip_labeled['index'].astype(str)
labels = hip_labeled[['index', 'topic_id', 'topic_label']].drop_duplicates(subset='index')

for target in APPEND_TARGETS:
    input_path = DATA_DIR / target['input']
    output_path = DATA_DIR / target['output']
    index_col = target['index_col']

    reduced = pd.read_csv(input_path)
    if index_col not in reduced.columns:
        print(f"Skipping {input_path}: missing join column '{index_col}'")
        continue

    reduced[index_col] = reduced[index_col].astype(str)

    merged = reduced.merge(labels, left_on=index_col, right_on='index', how='left')
    # Keep source index column when the join key itself is named 'index'.
    if index_col != 'index':
        merged = merged.drop(columns=['index'])

    missing = merged['topic_label'].isna().sum()

    merged.to_csv(output_path, index=False)
    print(f'Saved: {output_path} | Missing labels: {missing}')

Saved: ../data/final_labeled.csv | Missing labels: 0
Saved: ../data/final_deltamax_labeled.csv | Missing labels: 0
Saved: ../data/gemma4_raw_labeled.csv | Missing labels: 0
Saved: ../data/llama3.3_raw_labeled.csv | Missing labels: 0
Saved: ../data/qwen3_raw_labeled.csv | Missing labels: 0
Saved: ../data/study1_final_labeled.csv | Missing labels: 0
Saved: ../data/hippocorpus_test_truncated_80_100_labeled.csv | Missing labels: 0

Outputs:
- data/output.csv (or data/output_k_means.csv)
- data/topic_info.csv (or data/topic_info_k_means.csv)
- data/topic_name_suggestions.csv (optional LLM step)
- data/topic_info_named.csv (or data/topic_info_k_means_named.csv, optional apply step)
- data/hippocorpus_labeled.csv
- one labeled output per APPEND_TARGETS entry

## Step 7: Topic statistics overview for labeled CSVs

In [90]:
labeled_outputs = sorted({target['output'] for target in APPEND_TARGETS} | {'hippocorpus_labeled.csv'})

all_stats = []

for output_name in labeled_outputs:
    output_path = DATA_DIR / output_name
    if not output_path.exists():
        print(f'Skipping missing file: {output_path}')
        continue

    df = pd.read_csv(output_path)
    required_cols = {'topic_id', 'topic_label'}
    missing_cols = required_cols.difference(df.columns)
    if missing_cols:
        print(f"Skipping {output_name}: missing columns {sorted(missing_cols)}")
        continue

    stats = (
        df.groupby(['topic_id', 'topic_label'], dropna=False)
        .size()
        .rename('count')
        .reset_index()
    )
    stats['dataset'] = output_name
    stats['pct'] = (stats['count'] / len(df) * 100).round(2) if len(df) else 0.0
    all_stats.append(stats)

if all_stats:
    topic_stats_overview = pd.concat(all_stats, ignore_index=True)
    topic_stats_overview = topic_stats_overview[['dataset', 'topic_id', 'topic_label', 'count', 'pct']]
    topic_stats_overview = topic_stats_overview.sort_values(['dataset', 'count'], ascending=[True, False])

    overview_path = DATA_DIR / 'topic_stats_overview.csv'
    topic_stats_overview.to_csv(overview_path, index=False)

    print(f'Saved: {overview_path}')
    display(topic_stats_overview.head(50))

    dataset_totals = (
        topic_stats_overview.groupby('dataset', as_index=False)['count']
        .sum()
        .rename(columns={'count': 'rows'})
    )
    display(dataset_totals)
else:
    print('No labeled CSVs with topic columns were found.')

Saved: ../data/topic_stats_overview.csv

,dataset,topic_id,topic_label,count,pct
3,final_deltamax_labeled.csv,3,Hospital/Injury,70,17.33
6,final_deltamax_labeled.csv,7,Vacation/Trip,60,14.85
9,final_deltamax_labeled.csv,10,Work,60,14.85
8,final_deltamax_labeled.csv,9,Children,38,9.41
12,final_deltamax_labeled.csv,13,Relationships,30,7.43
1,final_deltamax_labeled.csv,1,Funeral/Death,28,6.93
0,final_deltamax_labeled.csv,0,Other,26,6.44
14,final_deltamax_labeled.csv,15,Family,22,5.45
10,final_deltamax_labeled.csv,11,School,18,4.46
7,final_deltamax_labeled.csv,8,Birthday,14,3.47
13,final_deltamax_labeled.csv,14,Sports,14,3.47
2,final_deltamax_labeled.csv,2,NaturalDisaster/Weather,8,1.98
11,final_deltamax_labeled.csv,12,Home/Moving,8,1.98
5,final_deltamax_labeled.csv,6,Concert/Music,6,1.49
4,final_deltamax_labeled.csv,5,Pets,2,0.50
21,final_labeled.csv,7,Vacation/Trip,361,17.15
18,final_labeled.csv,3,Hospital/Injury,352,16.72
24,final_labeled.csv,10,Work,250,11.88
16,final_labeled.csv,1,Funeral/Death,199,9.45
23,final_labeled.csv,9,Children,188,8.93
27,final_labeled.csv,13,Relationships,129,6.13
15,final_labeled.csv,0,Other,120,5.70
29,final_labeled.csv,15,Family,108,5.13
25,final_labeled.csv,11,School,94,4.47
22,final_labeled.csv,8,Birthday,90,4.28
28,final_labeled.csv,14,Sports,80,3.80
17,final_labeled.csv,2,NaturalDisaster/Weather,51,2.42
26,final_labeled.csv,12,Home/Moving,37,1.76
20,final_labeled.csv,6,Concert/Music,26,1.24
19,final_labeled.csv,5,Pets,20,0.95
36,gemma4_raw_labeled.csv,7,Vacation/Trip,51,15.45
33,gemma4_raw_labeled.csv,3,Hospital/Injury,48,14.55
42,gemma4_raw_labeled.csv,13,Relationships,38,11.52
30,gemma4_raw_labeled.csv,0,Other,34,10.30
39,gemma4_raw_labeled.csv,10,Work,33,10.00
38,gemma4_raw_labeled.csv,9,Children,27,8.18
44,gemma4_raw_labeled.csv,15,Family,26,7.88
31,gemma4_raw_labeled.csv,1,Funeral/Death,20,6.06
41,gemma4_raw_labeled.csv,12,Home/Moving,16,4.85
40,gemma4_raw_labeled.csv,11,School,11,3.33
35,gemma4_raw_labeled.csv,6,Concert/Music,7,2.12
37,gemma4_raw_labeled.csv,8,Birthday,6,1.82
43,gemma4_raw_labeled.csv,14,Sports,6,1.82
32,gemma4_raw_labeled.csv,2,NaturalDisaster/Weather,5,1.52
34,gemma4_raw_labeled.csv,4,Gambling,2,0.61
52,hippocorpus_labeled.csv,7,Vacation/Trip,853,16.90
48,hippocorpus_labeled.csv,3,Hospital/Injury,697,13.81
55,hippocorpus_labeled.csv,10,Work,589,11.67
54,hippocorpus_labeled.csv,9,Children,507,10.05
58,hippocorpus_labeled.csv,13,Relationships,467,9.25

                                         dataset  rows
0                     final_deltamax_labeled.csv   404
1                              final_labeled.csv  2105
2                         gemma4_raw_labeled.csv   330
3                        hippocorpus_labeled.csv  5047
4  hippocorpus_test_truncated_80_100_labeled.csv   262
5                       llama3.3_raw_labeled.csv   330
6                          qwen3_raw_labeled.csv   330
7                       study1_final_labeled.csv   330

In [91]:
# Deep dive for one labeled output
TARGET_OUTPUT = 'hippocorpus_test_truncated_80_100_labeled.csv'  # e.g., 'final_labeled.csv'
FILTER_TOPIC_LABEL = None  # e.g., 'Hospital/Injury'
TOP_N_TOPICS = 30
TOP_N_TEXTS_PER_TOPIC = 5
TEXT_PREVIEW_WIDTH = 220
SHOW_FULL_TEXT = True
FULL_TEXT_ROWS = 80

target_path = DATA_DIR / TARGET_OUTPUT
if not target_path.exists():
    raise FileNotFoundError(f'Missing file: {target_path}')

target_df = pd.read_csv(target_path)
required_cols = {'topic_id', 'topic_label'}
missing_cols = required_cols.difference(target_df.columns)
if missing_cols:
    raise ValueError(f"{TARGET_OUTPUT} is missing columns: {sorted(missing_cols)}")

topic_dist_target = (
    target_df.groupby(['topic_id', 'topic_label'], dropna=False)
    .size()
    .rename('count')
    .reset_index()
    .sort_values('count', ascending=False)
    .reset_index(drop=True)
)
topic_dist_target['pct'] = (topic_dist_target['count'] / len(target_df) * 100).round(2) if len(target_df) else 0.0

if FILTER_TOPIC_LABEL is not None:
    topic_dist_target = topic_dist_target[topic_dist_target['topic_label'] == FILTER_TOPIC_LABEL].reset_index(drop=True)

print(f'Deep dive dataset: {TARGET_OUTPUT} | Rows: {len(target_df):,}')
display(topic_dist_target.head(TOP_N_TOPICS))

if 'text' in target_df.columns:
    from textwrap import shorten
    if FILTER_TOPIC_LABEL is None:
        top_labels = topic_dist_target['topic_label'].head(TOP_N_TOPICS).tolist()
        subset = target_df[target_df['topic_label'].isin(top_labels)].copy()
    else:
        subset = target_df[target_df['topic_label'] == FILTER_TOPIC_LABEL].copy()

    sample_parts = []
    for _, grp in subset[['topic_label', 'text']].dropna(subset=['text']).groupby('topic_label'):
        sample_parts.append(grp.sample(min(TOP_N_TEXTS_PER_TOPIC, len(grp)), random_state=42))

    if sample_parts:
        sample_texts = pd.concat(sample_parts, ignore_index=True)
        sample_texts['text_preview'] = sample_texts['text'].astype(str).apply(
            lambda s: shorten(s.replace('\n', ' '), width=TEXT_PREVIEW_WIDTH, placeholder=' ...')
        )
        display(sample_texts[['topic_label', 'text_preview']])

        if SHOW_FULL_TEXT:
            print('\nFull text samples:')
            for i, row in enumerate(sample_texts.head(FULL_TEXT_ROWS).itertuples(index=False), start=1):
                print(f"\n[{i}] topic={row.topic_label}")
                print(row.text)
    else:
        print('No non-empty text rows available for sampling in this filter.')
else:
    print(f"{TARGET_OUTPUT} has no 'text' column, so text examples are not available.")

Deep dive dataset: hippocorpus_test_truncated_80_100_labeled.csv | Rows: 262

    topic_id              topic_label  count    pct
0          7            Vacation/Trip     46  17.56
1          3          Hospital/Injury     41  15.65
2         10                     Work     31  11.83
3         13            Relationships     26   9.92
4          9                 Children     22   8.40
5          0                    Other     21   8.02
6          1            Funeral/Death     18   6.87
7         15                   Family     18   6.87
8         11                   School     10   3.82
9         12              Home/Moving      9   3.44
10        14                   Sports      7   2.67
11         8                 Birthday      6   2.29
12         6            Concert/Music      4   1.53
13         2  NaturalDisaster/Weather      1   0.38
14         4                 Gambling      1   0.38
15         5                     Pets      1   0.38

   topic_label                                       text_preview
0     Birthday  Two weeks ago I hosted a birthday for Khloe. I...
1     Birthday  I had a good birthday. It was eventful and saw...
2     Birthday  It was during the first weekend of July when I...
3     Birthday  I had the time of my life two weeks ago. I had...
4     Birthday  Just a few months ago I was able to go to my b...
..         ...                                                ...
62        Work  One major event in my life is that in the past...
63        Work  I started a company within the past six months...
64        Work  It was a hot day in July that our community de...
65        Work  I retired from work six months ago. I had work...
66        Work  i am work in an manufacturing company. i were ...

[67 rows x 2 columns]

Full text samples:

[1] topic=Birthday
Two weeks ago I hosted a birthday for Khloe. I had planned this event so that I felt that everything should go well. I thought the day would be easy and successful. I got up early to pick up the final things for the party. I needed to pick up some helium filled balloons. I could not do this ahead of time since the helium would leak out. Next I went to pick up the cake. I wanted it to be as fresh as possible. Having done these last two chores, I returned home. When I unpacked my car, I realized that I had lost my wallet. Oh well, I will call these business concerns later and see if I can locate it. Everyone arrived and things seemed to be going well when out of nowhere Autumn puked. What a mess! I had to clean this up as quickly as possible and make the best of a messy situation. At least the cake was okay. Boy was I glad when this day was over. Everyone seemed to have a good time and now on to find my wallet. I made a few calls and was beginning to panic when some wonderful person knocked at my door and returned my wallet. What a day!

[2] topic=Birthday
I had a good birthday. It was eventful and saw lots of friends. Family too. It was a bigger party then I thought. Full of friends, and even more family. It was unexpected for the most part. I didn't know so much family was going to join. But they did and we had lots of fun. I had a blast introducing my friends to my family. I hadn't seen so many people get together so well. We ended up talking late into the night, way past the dinner time. And the cake they had was fun and huge. I had trouble blowing out the candle. So my many friends helped me out with it. And so many presents. I had a wonderful time.

[3] topic=Birthday
It was during the first weekend of July when I was finally able to do something that I hadn't been able to do in over 25 years. I was able to drag race for the first time since I was in my lower 20's.  While that was a big deal, the fact that I was able to race in a national event was huge. It had always been a lifelong dream for it to happen as I never figure that I would be able to buy a race car so I never thought that it was a possibility. But about two weeks before the race was going to take place, a really good friend surprised me and told be that he had always known that I wanted to race and that he wanted to make it happen. He had ran in several national events and I had been able to watch him do it on a couple of those occasions While he had never made it past the 2nd round in any of his attempts, he knew that I would love to give it a shot. My birthday was coming up and he said "that it was time for me to get my chance." At first, I thought that he was kidding but he was being honest. He told me that he had been working on the race car and that it was ready for me to run it. The weekend of the races, we headed to the track and did some qualifying passes. The car ran great although it took me a few runs to get used to the shift set-up that he had on the car. My reaction times were decent but they definitely weren't where I needed them to be for race day. We had a small engine issue pop up but nothing major and it was fixed in a short amount of time. My family enjoyed being able to see some of the racing greats that were there and my kid's really like getting autographs from them and getting to take pictures with them. It was expensive to do anything there but it was all about the memories that weekend. I wound up losing in the 1st round due to my poor reaction time. But either way, I was an experience that I will never forget.

[4] topic=Birthday
I had the time of my life two weeks ago. I had never felt that alive, and weirdly being a father was the reason for that feeling. Being a father at that point felt like the best thing that has ever happened to me. It was my daughter's birthday, she had so much that she could not stop talking about it for days. It was  two weeks ago but I can vividly remember everything that took place. Audrey was so full of joy, seeing her smile and laugh was probably the highlight of the year for me. Though planning and preparations for the birthday party was not an easy one. First I had to deal with the caterer, then there was the clown. The most annoying to deal with was magic-less magician. His magic almost bored kids to sleep. By some act of miracle the event turned out to be better than I expected. Everyone had so much fun, even the adults. All the kids were even reluctant to go home. I was so tired that night i slept for about 9 hours straight. The happiness and joy I saw on Audrey's face that day made it all worth it.

[5] topic=Birthday
Just a few months ago I was able to go to my best friend's daughters first birthday party. This was very exciting for me because this is my first close friend to have a child while I have two already and another that is due soon. Because we have been so busy since adulthood, her with work, and me being a mom, working, and going to school, it was a great opportunity to get together. My daughter was especially excited because she was really wanting the new baby to be a girl, but it is not. She has that opportunity to spend time with a baby girl. Even though they are not actually family, me and my friend have always been so close that the kids will be raised more like cousins than friends. I also got to see her family for the first time in a while which was nice. It felt like 'coming home.' This family is one that I have spent many holidays with over the years, including major holidays like Thanksgiving and Christmas that you typically spend with family. There were no other friends of the family at the party, it was only family members and that made me feel quite warm. It also was the first time I got to see my friends new house. She had been living with her spouse and baby at her mom's house since she was pregnant and it was very exciting to see them moving out and being more independent. While I love her family, it is always good to have your own space as an adult. I really look forward to our kids growing up together and couldn't be happier still. We even talked about having sleepovers with my 6 year old daughter and her 1 year old. I am feeling so excited about the future after this party.

[6] topic=Children
My son started college.  We loaded up both of our cars with all of his things and headed to his college which was 3 hours away.  This is our first child leaving for college so it is stressful, expensive and just sad.  It was even worse for me as my car's check engine light came on while we were driving him down. I had to say my goodbyes in a gas station parking lot which was less than ideal.  We managed to fit all of his stuff except his bike into one car and I drove back home in case something major was wrong with the car.  My wife finished driving him to school to unload all of his stuff.  My oldest daughter went with them to help but we didn't have room in that car for my younger daughter who I drove home.  I didn't even get to see his dorm room or campus or anything.  I miss him a lot as everything just seems different now that he is gone.  I text him regularly but it certainly isn't the same as seeing him all of the time.  He is coming back to visit on labor day so at least we have that going for us.  The car had some sort of electrical problem causing it to misfire, $800 later it is fixed.  My wife drove his bike down a week later.  The entire reason we took him to college early was for band camp.  He got accepted to the band but decided he didn't want to do it so turned them down.  Wish we had just waited 2 more weeks to move him in.

[7] topic=Children
Last week I invited some friends of mine to attend a class on love and yoga. During the class we began discussing the meaning of love, how it manifests itself in relationships and how it is seen within the universe. One of the things about the class that impressed me was the teacher's clarity that love is undefined and unconditioned. nit does not fluctuate much like the human conception, but instead it is a powerful force that can be said formed the universe. After the class we all had a chance to talk and converse what was shared. My friends were overjoyed that I would invite them to such a program because it was something that touched the hearts of all of us. Some people felt love was like An ocean in which we all swam or floated or drowned. Others felt that love was like a tree that ascended towards the heavens and humbled itself deep into the earth. Then there were some that felt love was a hummingbird that sought nectar from all of life. I could not help but agre with all three sentiments and feel that love takes many forms. some of these forms are seen in relationships between two people. Another form is between a parent and a child. There is also the form of love between friends which is most equal. There also exists a form of love between a teacher and a student. One can also see love between animals that care for their young or their mate. Love appears in many forms indeed. My feeling is that it's best to express rather to repress ones love. It's best to follow ones love.

[8] topic=Children
Tae Kwon Do has been a passion of mine since I was a small kid. I grew up in a household remind mom and dad were both really into fitness. My mom had recommended to me Tae Kwon Do so that's what I did. I fell in love with it right away and moved up the ranks. While other kids were at school practicing football and baseball I would be at the Dojo learning all I could. Fast forward about a month ago it was finally time for me to go for my red belt. Practice had become my life because achieving this belt meant everything to me. I went through my entire repertoire while filming myself. I wanted to see where I could improve. I took not and practiced what I needed.  At that point I felt that I had the discipline and skill necessary to achieve the rank. In the weeks leading up to this I continued to practice night and day. I felt muscles in my body that I didn't even know existed, but it all paid off in the end. When I receive my red belt it felt like a crowning achievement. To this day I'm still really proud of this and I plan on getting better and better in this amazing sport.

[9] topic=Children
About 3 months ago, I started to notice some weird sensations in my chest. It happened pretty infrequently at first, and I just sort of ignored it. It bothered me of course, but I figured it was nothing. I am too busy with my kid to get sick. I should be able to power through illness, right? My kid comes first. I ignored the warning signs. But then it started to happen more frequently over the course of a couple of days. It started to become more painful. The pain got bad enough that it started to take my breath away. This all escalated so quickly over the course of a couple of days. Finally I couldn't ignore it anymore.  My spouse noticed and told me I needed to go to the ER, I could be having a heart attack. So he loaded me and my kid up and we drove to the ER. I had to get a lot of tests done, and I wish I would have gone in sooner. I am ok now, but I will never ignore something like that again.

[10] topic=Children
I recently had a few different drastically life changing events take place. One of which is the beginning of a divorce. After ten years of marriage, my husband decided he wanted a divorce. After some of the awful things he did in our marriage, I was still hanging in hoping we could move past all the hurt and betrayal. But unfortunately, he got fed up with the process and decided to end it. Just within the last three months I have agreed to give him the divorce, had him lash out at me in unspeakable ways, been forced to move due to lack of ability to continue paying for the previous place and had to pick up the pieces for myself and my three young children. I thank God that he has given me several people in my life that have been there for me and helped me through all of this. Without them, it would have been way worse. I am still trying to get through this divorce, but I have faith that the Lord will work all this for good. Many other changes have come along with this divorce. Of course the move. The change in family dynamic, which has been the worst and most difficult change. The financial changes. The emotional changes in me, which I struggle with every single day. The coping of my children. Yes, this has been quite the emotional roller coaster. I am still looking to the Lord for daily strength.

[11] topic=Concert/Music
For years I played bass in a a fairly popular band that toured around the world but stopped  a few years ago. This last July the band reformed and traveled to Bogota, Colombia to play a show. It was fun and a bit surreal to reunite and work with the other members after all the time off. It was also pretty humorous to see how quickly we all settled in to our old behaviors. Traveling as a group can be stressful especially when you have to transport instruments that the TSA views with suspicion and attempts to disassemble, which is what happened to me. Thankfully I was able to get everything working for the concert.  We had a full day in Bogota before the show, which we spent hanging out with a promoter with whom we had worked before on a previous trip. He took us to local restaurants and record stores which we never would have stumbled on by ourselves. Then that evening there was a party at a record store in kind of a hipster area of town. After that we headed to a small jazz club where the drummer from the band we were sharing the bill with was playing. It was a small cafe with a prominently displayed triptych of chairman Mao. There are very good painters in Bogota and there are very elaborate murals to be seen everywhere and even the graffiti approaches high art. The show was a double bill with another band and took place in a very large 5000 seat auditorium, even though neither band had the capacity to draw that many people. Even though the whole organization was very professionally run, sound check seemed to last forever and resulted in my not being able to have lunch with an old friend who I hadn't seen for years. But the concert itself went well there was a good showing on the ground floor seats, but the balconies remained unused. Afterwards I was able to meet up with my friend and go out for some drinks. The day after the show was spent in the studio collaborating with the band with whom we had shared the bill, and felt like equal parts work and social occasion. Some friends of the other band who are foodie types, prepared a meal for everyone, and there was plenty of beer and wine and general frivolity. Our last day in Bogota was open so the guitarist and keyboardist and I went to the National museum, which is a sprawling, long and narrow building with lots of interactive exhibits on everything about Colombian culture past and present.  Afterwards we had lunch at a Peruvian restaurant which, ironically was some of the best food we had in Colombia. That was followed by lots of walking through flea markets and street fairs that spring up during the weekend. Then it was time to make our way to the airport for our red eye flight back to New York.

[12] topic=Concert/Music
Last Wednesday, I went to see the band Kero Kero Bonito perform at the Union Transfer concert venue in Philadelphia, PA. During their performance, I found myself singing along to all of their songs and dancing with other members of the crowd. While I did not know anyone else in the crowd, I felt a oneness with them, as we were all fans of the band and knew all of the songs by heart. I had had two beers before the concert, but the euphoria I felt while dancing with other fans was a different sort of intoxication that did not require alcohol at all. We jumped, sang our lungs out, and stepped back and forth frantically. When the singer needed us to clap, stomp, or carry the tune, we obliged. The night passed by in a flash as our adrenaline and sweat flowed like water. It was the most fun I had had in a while. I had sung and shouted so much that my voice was gone the next morning. It made me think about seeing another band at that venue in the near future. This was the closest thing to a religious experience that I had had happen to me. Short of converting to a religion, another event like this was my best shot at feeling it again. I will always remember this night as one where I joined with complete strangers to appreciate our favorite band. As we walked out into the lobby, we lined up to buy band merchandise. While I didn't really need to buy anything, I wanted to get a shirt or a CD to commemorate the night we had. I bought a signed CD and a sweatshirt before walking out into the brisk fall night.

[13] topic=Concert/Music
I was ecstatic when my childhood friend called me one day, out of the blue in a Saturday morning 4 months ago. I was surprised to see his name come up on my phone - I haven't seem him since high school. He knew that I was a aspiring photographer that was looking for gigs. When he told me that he was engaged and wanted me to take pictures for a secret wedding, I was jumping up and down on the subway train. My first solo gig was going to be for a friend's secret wedding! I prepared for weeks, taking many as many practice shots as I could. My friend and his wife was gorgeous on that day - it was just me, them, and their families. It was a great honor for me to be their photographer, and the wedding was held at a wedding venue filled to the brim with bright lights. It was every photographer's dream - to take pictures in such an grand environment. My friend and I did a lot of catching up - after high school, he went to college where he majored in actuarial science, and is now a successful accountant. I thanked him for giving me this opportunity. The food was great - everyone was served beer and lobster. I took hundreds of photos that day. Everyone had a great time. I can't wait to develop the film photos!

[14] topic=Concert/Music
Well I had just about the nicest birthday of my life this last weekend. I wasn't expecting much, honestly, because we are not rich by any means and usually birthdays are a pretty simple affair. After a delicious home-cooked dinner, my husband and I were just about to dig into some cake when he slipped away to our bedroom to receive a wrapped gift. I was already so surprised, since we don't typically do gifts. He looked so excited giving it to me, I couldn't help but tear into it. Inside I found concert tickets! This was really thrilling because we haven't been out to see anything live in years and I've been dreaming of doing something just like this. What really got me, though, was when I noticed that the tickets were to go see Paul McCartney! The Beatles (and Paul) have honestly always been my favorite since I was a child, but I never imagined I'd go and see one of them live. I was so touched, and my husband just had the cutest smile on his face. I didn't want to say anything, but I know that the tickets must have been pretty expensive and it would have taken him a long time to save up for them. I just think it's one of the sweetest things he has ever done for me. The next night we went out for dinner before catching the show and the whole thing was just a dream. We had so much fun and I felt ten years younger! We danced and sang along together, and when we went home we both couldn't stop talking about how great the show had been. I don't think I will ever forget this birthday, it was such a delight.

[15] topic=Family

In [41]:
# Verify assigned topic labels against current regex rules
VERIFY_OUTPUT = TARGET_OUTPUT  # set explicitly if needed
CHECK_ROWS = None  # set int to sample N rows for faster checks, e.g., 2000
SHOW_ONLY_MISMATCHES = True
MISMATCH_PREVIEW = 30
VERIFY_TEXT_PREVIEW_WIDTH = 220

verify_path = DATA_DIR / VERIFY_OUTPUT
if not verify_path.exists():
    raise FileNotFoundError(f'Missing file: {verify_path}')

verify_df = pd.read_csv(verify_path)
required_cols = {'topic_label', 'text'}
missing_cols = required_cols.difference(verify_df.columns)
if missing_cols:
    raise ValueError(
        f"{VERIFY_OUTPUT} is missing required columns for verification: {sorted(missing_cols)}"
    )

if CHECK_ROWS is not None and CHECK_ROWS > 0 and len(verify_df) > CHECK_ROWS:
    verify_df = verify_df.sample(CHECK_ROWS, random_state=42).reset_index(drop=True)

def matched_topics(text):
    text_str = str(text)
    return [label for _, label, pattern in RULES if pattern.search(text_str)]

verify_df = verify_df.copy()
verify_df['matched_topics'] = verify_df['text'].apply(matched_topics)
verify_df['first_matched_topic'] = verify_df['matched_topics'].apply(lambda topics: topics[0] if topics else 'Other')
verify_df['n_matched_topics'] = verify_df['matched_topics'].apply(len)
verify_df['assigned_is_first_match'] = verify_df['topic_label'] == verify_df['first_matched_topic']
verify_df['assigned_in_any_match'] = verify_df.apply(
    lambda row: (row['topic_label'] in row['matched_topics']) if row['topic_label'] != 'Other' else (len(row['matched_topics']) == 0),
    axis=1,
 )
verify_df['is_ambiguous'] = verify_df['n_matched_topics'] > 1

summary = (
    verify_df.groupby('topic_label', dropna=False)
    .agg(
        total=('topic_label', 'size'),
        first_match_ok=('assigned_is_first_match', 'sum'),
        any_match_ok=('assigned_in_any_match', 'sum'),
        ambiguous_rows=('is_ambiguous', 'sum'),
    )
    .reset_index()
    .sort_values('total', ascending=False)
    .reset_index(drop=True)
)
summary['first_match_rate_pct'] = (summary['first_match_ok'] / summary['total'] * 100).round(2)
summary['any_match_rate_pct'] = (summary['any_match_ok'] / summary['total'] * 100).round(2)
summary['ambiguous_rate_pct'] = (summary['ambiguous_rows'] / summary['total'] * 100).round(2)

overall_first_match_rate = verify_df['assigned_is_first_match'].mean() * 100 if len(verify_df) else 0.0
overall_ambiguous_rate = verify_df['is_ambiguous'].mean() * 100 if len(verify_df) else 0.0

print(f'Verification dataset: {VERIFY_OUTPUT} | Rows checked: {len(verify_df):,}')
print(f'Overall first-match consistency (meaningful): {overall_first_match_rate:.2f}%')
print(f'Overall multi-hit ambiguity: {overall_ambiguous_rate:.2f}%')
display(summary[['topic_label', 'total', 'first_match_rate_pct', 'any_match_rate_pct', 'ambiguous_rate_pct']])

to_show = verify_df[~verify_df['assigned_is_first_match']].copy()
if SHOW_ONLY_MISMATCHES:
    pass
else:
    to_show = verify_df.copy()

if not to_show.empty:
    from textwrap import shorten
    to_show['text_preview'] = to_show['text'].astype(str).apply(
        lambda s: shorten(s.replace('\n', ' '), width=VERIFY_TEXT_PREVIEW_WIDTH, placeholder=' ...')
    )
    display(
        to_show[['topic_label', 'first_matched_topic', 'n_matched_topics', 'matched_topics', 'text_preview']]
        .head(MISMATCH_PREVIEW)
    )
else:
    print('No first-match mismatches found with current settings.')

Verification dataset: hippocorpus_test_truncated_80_100_labeled.csv | Rows checked: 262
Overall first-match consistency (meaningful): 100.00%
Overall multi-hit ambiguity: 69.08%

,topic_label,total,first_match_rate_pct,any_match_rate_pct,ambiguous_rate_pct
0,Work,43,100.0,100.0,69.77
1,Hospital/Injury,40,100.0,100.0,90.00
2,Vacation/Trip,39,100.0,100.0,76.92
3,Children,20,100.0,100.0,90.00
4,Relationships,20,100.0,100.0,45.00
5,Funeral/Death,18,100.0,100.0,94.44
6,Other,18,100.0,100.0,0.00
7,Money/Gambling,14,100.0,100.0,92.86
8,Family,11,100.0,100.0,0.00
9,Pets,10,100.0,100.0,90.00
10,Concert/Music,9,100.0,100.0,88.89
11,School,8,100.0,100.0,37.50
12,Birthday,4,100.0,100.0,100.00
13,Home/Moving,4,100.0,100.0,50.00
14,Sports,3,100.0,100.0,33.33
15,NaturalDisaster/Weather,1,100.0,100.0,100.00

No first-match mismatches found with current settings.